name: agnostic-automation-center

services:
  # -------------------------
  # Infrastructure
  # -------------------------
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - ./npm-data:/data
      - ./npm-letsencrypt:/etc/letsencrypt
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: automation-rabbitmq
    restart: always
    expose:
      - "5672"
      - "15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: automation-redis
    restart: always
    expose:
      - "6379"
    networks:
      - app-network

  # -------------------------
  # App Services
  # -------------------------
  producer:
    build:
      context: .
      dockerfile: apps/producer-service/Dockerfile
    container_name: automation-producer
    restart: always
    volumes:
      - test_results:/app/reports
    env_file:
      - .env
    environment:
      - PORT=3000
      - RABBITMQ_URL=amqp://rabbitmq
      - MONGO_URI=${MONGO_URI}
      - MONGODB_URL=${MONGO_URI}
      - REPORTS_DIR=/app/reports
      - REDIS_URL=redis://redis:6379
    depends_on:
      - rabbitmq
      - redis
    networks:
      - app-network

  worker:
    build:
      context: .
      dockerfile: apps/worker-service/Dockerfile
    container_name: automation-worker
    restart: always
    environment:
      - RUNNING_IN_DOCKER=true
      - RABBITMQ_URL=amqp://rabbitmq
      - MONGO_URI=${MONGO_URI}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - BASE_URL=${BASE_URL}
      - PRODUCER_URL=http://producer:3000
      - REPORTS_DIR=/app/reports
      - PUBLIC_API_URL=${PUBLIC_API_URL}
      - REDIS_URL=redis://redis:6379
      - CI=true
      - GITHUB_COPILOT_API_KEY=${GITHUB_COPILOT_API_KEY}
    volumes:
      - test_results:/app/reports
      - /var/run/docker.sock:/var/run/docker.sock 
    depends_on:
      - rabbitmq
      - producer
      - redis
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  dashboard:
    build:
      context: .
      dockerfile: apps/dashboard-client/Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: automation-dashboard
    restart: always
    depends_on:
      - producer
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  test_results:
    driver: local